// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCew7Zzq3Q6pt3aOO6cF2qTun0ghbFcvZc',
    appId: '1:383118763711:android:d7881fe2e476441690c80a',
    messagingSenderId: '383118763711',
    projectId: 'wut-zajka-mova',
    storageBucket: 'wut-zajka-mova.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCns55XF7dwTnYDsOCQDmCZlbUcQ89hkRA',
    appId: '1:383118763711:ios:4e40bc926efb214d90c80a',
    messagingSenderId: '383118763711',
    projectId: 'wut-zajka-mova',
    storageBucket: 'wut-zajka-mova.appspot.com',
    iosClientId: '383118763711-ebk4csasapf2jkmip4082jmua3oh3r9s.apps.googleusercontent.com',
    iosBundleId: 'pl.zajka.mova',
  );
}
